# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srjdjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquirymodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=200)),
                ('organization_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20015)),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
    ]
