# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srjdjango', '0002_enquirymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirymodel',
            name='organization_name',
        ),
    ]
