# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-05-06 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srjdjango', '0003_remove_enquirymodel_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirymodel',
            name='contact_number',
            field=models.CharField(max_length=215),
        ),
    ]
